/**
 *
 */
package pl.edu.wat.wcy.cop.app.client.utils.images;

import pl.edu.wat.wcy.cop.app.shared.AppConstants;
import pl.edu.wat.wcy.cop.app.shared.domain.PointOfInterestTypeDto;
// Maps poi type to marker image data.


public class PoiTypeToMarkerImageMapper {

    /**
     * Zwracany jest string base64
     *
     * @param type
     * @return
     */
    public static String getImageSourceForPoiType(PointOfInterestTypeDto type) {
        if (type == null) {
            return AppConstants.POI_ICON_URL;
        }
        return getMarkerResource(type);
    }

    private static String getMarkerResource(PointOfInterestTypeDto type) {
        switch (type) {
            case ABSEILING:
                return MarkerImages.INSTANCE.abseiling().getSafeUri().asString();
            case ACCOUNTING:
                return MarkerImages.INSTANCE.accounting().getSafeUri().asString();
            case AIRPORT:
                return MarkerImages.INSTANCE.airport().getSafeUri().asString();
            case AMUSEMENT_PARK:
                return MarkerImages.INSTANCE.amusement_park().getSafeUri().asString();
            case AQUARIUM:
                return MarkerImages.INSTANCE.aquarium().getSafeUri().asString();
            case ARCHERY:
                return MarkerImages.INSTANCE.archery().getSafeUri().asString();
            case ART_GALLERY:
                return MarkerImages.INSTANCE.art_gallery().getSafeUri().asString();
            case ATM:
                return MarkerImages.INSTANCE.atm().getSafeUri().asString();
            case BAKERY:
                return MarkerImages.INSTANCE.bakery().getSafeUri().asString();
            case BANK:
                return MarkerImages.INSTANCE.bank().getSafeUri().asString();
            case BAR:
                return MarkerImages.INSTANCE.bar().getSafeUri().asString();
            case BASEBALL:
                return MarkerImages.INSTANCE.baseball().getSafeUri().asString();
            case BEAUTY_SALON:
                return MarkerImages.INSTANCE.beauty_salon().getSafeUri().asString();
            case BICYCLE_STORE:
                return MarkerImages.INSTANCE.bicycle_store().getSafeUri().asString();
            case BICYCLING:
                return MarkerImages.INSTANCE.bicycling().getSafeUri().asString();
            case BOAT_RAMP:
                return MarkerImages.INSTANCE.boat_ramp().getSafeUri().asString();
            case BOAT_TOUR:
                return MarkerImages.INSTANCE.boat_tour().getSafeUri().asString();
            case BOATING:
                return MarkerImages.INSTANCE.boating().getSafeUri().asString();
            case BOOK_STORE:
                return MarkerImages.INSTANCE.book_store().getSafeUri().asString();
            case BOWLING_ALLEY:
                return MarkerImages.INSTANCE.bowling_alley().getSafeUri().asString();
            case BRAILLE:
                return MarkerImages.INSTANCE.braille().getSafeUri().asString();
            case BUS_STATION:
                return MarkerImages.INSTANCE.bus_station().getSafeUri().asString();
            case CAFE:
                return MarkerImages.INSTANCE.cafe().getSafeUri().asString();
            case CAMPGROUND:
                return MarkerImages.INSTANCE.campground().getSafeUri().asString();
            case CANOE:
                return MarkerImages.INSTANCE.canoe().getSafeUri().asString();
            case CAR_DEALER:
                return MarkerImages.INSTANCE.car_dealer().getSafeUri().asString();
            case CAR_RENTAL:
                return MarkerImages.INSTANCE.car_rental().getSafeUri().asString();
            case CAR_REPAIR:
                return MarkerImages.INSTANCE.car_repair().getSafeUri().asString();
            case CAR_WASH:
                return MarkerImages.INSTANCE.car_wash().getSafeUri().asString();
            case CASINO:
                return MarkerImages.INSTANCE.casino().getSafeUri().asString();
            case CEMETERY:
                return MarkerImages.INSTANCE.cemetery().getSafeUri().asString();
            case CHAIRLIFT:
                return MarkerImages.INSTANCE.chairlift().getSafeUri().asString();
            case CHURCH:
                return MarkerImages.INSTANCE.church().getSafeUri().asString();
            case CIRCLE:
                return MarkerImages.INSTANCE.circle().getSafeUri().asString();
            case CITY_HALL:
                return MarkerImages.INSTANCE.city_hall().getSafeUri().asString();
            case CLIMBING:
                return MarkerImages.INSTANCE.climbing().getSafeUri().asString();
            case CLOSED_CAPTIONING:
                return MarkerImages.INSTANCE.closed_captioning().getSafeUri().asString();
            case CLOTHING_STORE:
                return MarkerImages.INSTANCE.clothing_store().getSafeUri().asString();
            case COMPASS:
                return MarkerImages.INSTANCE.compass().getSafeUri().asString();
            case CONVENIENCE_STORE:
                return MarkerImages.INSTANCE.convenience_store().getSafeUri().asString();
            case COURTHOUSE:
                return MarkerImages.INSTANCE.courthouse().getSafeUri().asString();
            case CROSS_COUNTRY_SKIING:
                return MarkerImages.INSTANCE.cross_country_skiing().getSafeUri().asString();
            case CROSSHAIRS:
                return MarkerImages.INSTANCE.crosshairs().getSafeUri().asString();
            case DENTIST:
                return MarkerImages.INSTANCE.dentist().getSafeUri().asString();
            case DEPARTMENT_STORE:
                return MarkerImages.INSTANCE.department_store().getSafeUri().asString();
            case DIVING:
                return MarkerImages.INSTANCE.diving().getSafeUri().asString();
            case DOCTOR:
                return MarkerImages.INSTANCE.doctor().getSafeUri().asString();
            case ELECTRICIAN:
                return MarkerImages.INSTANCE.electrician().getSafeUri().asString();
            case ELECTRONICS_STORE:
                return MarkerImages.INSTANCE.electronics_store().getSafeUri().asString();
            case EMBASSY:
                return MarkerImages.INSTANCE.embassy().getSafeUri().asString();
            case EXPAND:
                return MarkerImages.INSTANCE.expand().getSafeUri().asString();
            case FEMALE:
                return MarkerImages.INSTANCE.female().getSafeUri().asString();
            case FINANCE:
                return MarkerImages.INSTANCE.finance().getSafeUri().asString();
            case FIRE_STATION:
                return MarkerImages.INSTANCE.fire_station().getSafeUri().asString();
            case FISH_CLEANING:
                return MarkerImages.INSTANCE.fish_cleaning().getSafeUri().asString();
            case FISHING_PIER:
                return MarkerImages.INSTANCE.fishing_pier().getSafeUri().asString();
            case FISHING:
                return MarkerImages.INSTANCE.fishing().getSafeUri().asString();
            case FLORIST:
                return MarkerImages.INSTANCE.florist().getSafeUri().asString();
            case FOOD:
                return MarkerImages.INSTANCE.food().getSafeUri().asString();
            case FULLSCREEN:
                return MarkerImages.INSTANCE.fullscreen().getSafeUri().asString();
            case FUNERAL_HOME:
                return MarkerImages.INSTANCE.funeral_home().getSafeUri().asString();
            case FURNITURE_STORE:
                return MarkerImages.INSTANCE.furniture_store().getSafeUri().asString();
            case GAS_STATION:
                return MarkerImages.INSTANCE.gas_station().getSafeUri().asString();
            case GENERAL_CONTRACTOR:
                return MarkerImages.INSTANCE.general_contractor().getSafeUri().asString();
            case GOLF:
                return MarkerImages.INSTANCE.golf().getSafeUri().asString();
            case GROCERY_OR_SUPERMARKET:
                return MarkerImages.INSTANCE.grocery_or_supermarket().getSafeUri().asString();
            case GYM:
                return MarkerImages.INSTANCE.gym().getSafeUri().asString();
            case HAIR_CARE:
                return MarkerImages.INSTANCE.hair_care().getSafeUri().asString();
            case HANG_GLIDING:
                return MarkerImages.INSTANCE.hang_gliding().getSafeUri().asString();
            case HARDWARE_STORE:
                return MarkerImages.INSTANCE.hardware_store().getSafeUri().asString();
            case HEALTH:
                return MarkerImages.INSTANCE.health().getSafeUri().asString();
            case HINDU_TEMPLE:
                return MarkerImages.INSTANCE.hindu_temple().getSafeUri().asString();
            case HORSE_RIDING:
                return MarkerImages.INSTANCE.horse_riding().getSafeUri().asString();
            case HOSPITAL:
                return MarkerImages.INSTANCE.hospital().getSafeUri().asString();
            case ICE_FISHING:
                return MarkerImages.INSTANCE.ice_fishing().getSafeUri().asString();
            case ICE_SKATING:
                return MarkerImages.INSTANCE.ice_skating().getSafeUri().asString();
            case INLINE_SKATING:
                return MarkerImages.INSTANCE.inline_skating().getSafeUri().asString();
            case INSURANCE_AGENCY:
                return MarkerImages.INSTANCE.insurance_agency().getSafeUri().asString();
            case JET_SKIING:
                return MarkerImages.INSTANCE.jet_skiing().getSafeUri().asString();
            case JEWELRY_STORE:
                return MarkerImages.INSTANCE.jewelry_store().getSafeUri().asString();
            case KAYAKING:
                return MarkerImages.INSTANCE.kayaking().getSafeUri().asString();
            case LAUNDRY:
                return MarkerImages.INSTANCE.laundry().getSafeUri().asString();
            case LAWYER:
                return MarkerImages.INSTANCE.lawyer().getSafeUri().asString();
            case LIBRARY:
                return MarkerImages.INSTANCE.library().getSafeUri().asString();
            case LIQUOR_STORE:
                return MarkerImages.INSTANCE.liquor_store().getSafeUri().asString();
            case LOCAL_GOVERNMENT:
                return MarkerImages.INSTANCE.local_government().getSafeUri().asString();
            case LOCATION_ARROW:
                return MarkerImages.INSTANCE.location_arrow().getSafeUri().asString();
            case LOCKSMITH:
                return MarkerImages.INSTANCE.locksmith().getSafeUri().asString();
            case LODGING:
                return MarkerImages.INSTANCE.lodging().getSafeUri().asString();
            case LOW_VISION_ACCESS:
                return MarkerImages.INSTANCE.low_vision_access().getSafeUri().asString();
            case MALE:
                return MarkerImages.INSTANCE.male().getSafeUri().asString();
            case MAP_PIN:
                return MarkerImages.INSTANCE.map_pin().getSafeUri().asString();
            case MARINA:
                return MarkerImages.INSTANCE.marina().getSafeUri().asString();
            case MARKER:
                return AppConstants.POI_ICON_URL;
            case MOSQUE:
                return MarkerImages.INSTANCE.mosque().getSafeUri().asString();
            case MOTOBIKE_TRAIL:
                return MarkerImages.INSTANCE.motobike_trail().getSafeUri().asString();
            case MOVIE_RENTAL:
                return MarkerImages.INSTANCE.movie_rental().getSafeUri().asString();
            case MOVIE_THEATER:
                return MarkerImages.INSTANCE.movie_theater().getSafeUri().asString();
            case MOVING_COMPANY:
                return MarkerImages.INSTANCE.moving_company().getSafeUri().asString();
            case MUSEUM:
                return MarkerImages.INSTANCE.museum().getSafeUri().asString();
            case NATURAL_FEATURE:
                return MarkerImages.INSTANCE.natural_feature().getSafeUri().asString();
            case NIGHT_CLUB:
                return MarkerImages.INSTANCE.night_club().getSafeUri().asString();
            case OPEN_CAPTIONING:
                return MarkerImages.INSTANCE.open_captioning().getSafeUri().asString();
            case PAINTER:
                return MarkerImages.INSTANCE.painter().getSafeUri().asString();
            case PARK:
                return MarkerImages.INSTANCE.park().getSafeUri().asString();
            case PARKING:
                return MarkerImages.INSTANCE.parking().getSafeUri().asString();
            case PET_STORE:
                return MarkerImages.INSTANCE.pet_store().getSafeUri().asString();
            case PHARMACY:
                return MarkerImages.INSTANCE.pharmacy().getSafeUri().asString();
            case PHYSIOTHERAPIST:
                return MarkerImages.INSTANCE.physiotherapist().getSafeUri().asString();
            case PLACE_OF_WORSHIP:
                return MarkerImages.INSTANCE.place_of_worship().getSafeUri().asString();
            case PLAYGROUND:
                return MarkerImages.INSTANCE.playground().getSafeUri().asString();
            case PLUMBER:
                return MarkerImages.INSTANCE.plumber().getSafeUri().asString();
            case POINT_OF_INTEREST:
                return MarkerImages.INSTANCE.point_of_interest().getSafeUri().asString();
            case POLICE:
                return MarkerImages.INSTANCE.police().getSafeUri().asString();
            case POLITICAL:
                return MarkerImages.INSTANCE.political().getSafeUri().asString();
            case POST_BOX:
                return MarkerImages.INSTANCE.post_box().getSafeUri().asString();
            case POST_OFFICE:
                return MarkerImages.INSTANCE.post_office().getSafeUri().asString();
            case POSTAL_CODE_PREFIX:
                return MarkerImages.INSTANCE.postal_code_prefix().getSafeUri().asString();
            case POSTAL_CODE:
                return MarkerImages.INSTANCE.postal_code().getSafeUri().asString();
            case RAFTING:
                return MarkerImages.INSTANCE.rafting().getSafeUri().asString();
            case REAL_ESTATE_AGENCY:
                return MarkerImages.INSTANCE.real_estate_agency().getSafeUri().asString();
            case RESTAURANT:
                return MarkerImages.INSTANCE.restaurant().getSafeUri().asString();
            case ROOFING_CONTRACTOR:
                return MarkerImages.INSTANCE.roofing_contractor().getSafeUri().asString();
            case ROUTE_PIN:
                return MarkerImages.INSTANCE.route_pin().getSafeUri().asString();
            case ROUTE:
                return MarkerImages.INSTANCE.route().getSafeUri().asString();
            case RV_PARK:
                return MarkerImages.INSTANCE.rv_park().getSafeUri().asString();
            case SAILING:
                return MarkerImages.INSTANCE.sailing().getSafeUri().asString();
            case SCHOOL:
                return MarkerImages.INSTANCE.school().getSafeUri().asString();
            case SCUBA_DIVING:
                return MarkerImages.INSTANCE.scuba_diving().getSafeUri().asString();
            case SEARCH:
                return MarkerImages.INSTANCE.search().getSafeUri().asString();
            case SHEILD:
                return MarkerImages.INSTANCE.sheild().getSafeUri().asString();
            case SHOPPING_MALL:
                return MarkerImages.INSTANCE.shopping_mall().getSafeUri().asString();
            case SIGN_LANGUAGE:
                return MarkerImages.INSTANCE.sign_language().getSafeUri().asString();
            case SKATEBOARDING:
                return MarkerImages.INSTANCE.skateboarding().getSafeUri().asString();
            case SKI_JUMPING:
                return MarkerImages.INSTANCE.ski_jumping().getSafeUri().asString();
            case SKIING:
                return MarkerImages.INSTANCE.skiing().getSafeUri().asString();
            case SLEDDING:
                return MarkerImages.INSTANCE.sledding().getSafeUri().asString();
            case SNOW_SHOEING:
                return MarkerImages.INSTANCE.snow_shoeing().getSafeUri().asString();
            case SNOW:
                return MarkerImages.INSTANCE.snow().getSafeUri().asString();
            case SNOWBOARDING:
                return MarkerImages.INSTANCE.snowboarding().getSafeUri().asString();
            case SNOWMOBILE:
                return MarkerImages.INSTANCE.snowmobile().getSafeUri().asString();
            case SPA:
                return MarkerImages.INSTANCE.spa().getSafeUri().asString();
            case SQUARE_PIN:
                return MarkerImages.INSTANCE.square_pin().getSafeUri().asString();
            case SQUARE_ROUNDED:
                return MarkerImages.INSTANCE.square_rounded().getSafeUri().asString();
            case SQUARE:
                return MarkerImages.INSTANCE.square().getSafeUri().asString();
            case STADIUM:
                return MarkerImages.INSTANCE.stadium().getSafeUri().asString();
            case STORAGE:
                return MarkerImages.INSTANCE.storage().getSafeUri().asString();
            case STORE:
                return MarkerImages.INSTANCE.store().getSafeUri().asString();
            case SUBWAY_STATION:
                return MarkerImages.INSTANCE.subway_station().getSafeUri().asString();
            case SURFING:
                return MarkerImages.INSTANCE.surfing().getSafeUri().asString();
            case SWIMMING:
                return MarkerImages.INSTANCE.swimming().getSafeUri().asString();
            case SYNAGOGUE:
                return MarkerImages.INSTANCE.synagogue().getSafeUri().asString();
            case TAXI_STAND:
                return MarkerImages.INSTANCE.taxi_stand().getSafeUri().asString();
            case TENNIS:
                return MarkerImages.INSTANCE.tennis().getSafeUri().asString();
            case TOILET:
                return MarkerImages.INSTANCE.toilet().getSafeUri().asString();
            case TRAIL_WALKING:
                return MarkerImages.INSTANCE.trail_walking().getSafeUri().asString();
            case TRAIN_STATION:
                return MarkerImages.INSTANCE.train_station().getSafeUri().asString();
            case TRANSIT_STATION:
                return MarkerImages.INSTANCE.transit_station().getSafeUri().asString();
            case TRAVEL_AGENCY:
                return MarkerImages.INSTANCE.travel_agency().getSafeUri().asString();
            case UNISEX:
                return MarkerImages.INSTANCE.unisex().getSafeUri().asString();
            case UNIVERSITY:
                return MarkerImages.INSTANCE.university().getSafeUri().asString();
            case VETERINARY_CARE:
                return MarkerImages.INSTANCE.veterinary_care().getSafeUri().asString();
            case VIEWING:
                return MarkerImages.INSTANCE.viewing().getSafeUri().asString();
            case VOLUME_CONTROL_TELEPHONE:
                return MarkerImages.INSTANCE.volume_control_telephone().getSafeUri().asString();
            case WALKING:
                return MarkerImages.INSTANCE.walking().getSafeUri().asString();
            case WATERSKIING:
                return MarkerImages.INSTANCE.waterskiing().getSafeUri().asString();
            case WHALE_WATCHING:
                return MarkerImages.INSTANCE.whale_watching().getSafeUri().asString();
            case WHEELCHAIR:
                return MarkerImages.INSTANCE.wheelchair().getSafeUri().asString();
            case WIND_SURFING:
                return MarkerImages.INSTANCE.wind_surfing().getSafeUri().asString();
            case ZOO:
                return MarkerImages.INSTANCE.zoo().getSafeUri().asString();
            case ZOOM_IN_ALT:
                return MarkerImages.INSTANCE.zoom_in_alt().getSafeUri().asString();
            case ZOOM_IN:
                return MarkerImages.INSTANCE.zoom_in().getSafeUri().asString();
            case ZOOM_OUT_ALT:
                return MarkerImages.INSTANCE.zoom_out_alt().getSafeUri().asString();
            case ZOOM_OUT:
                return MarkerImages.INSTANCE.zoom_out().getSafeUri().asString();
            case SAPOS:
                return MarkerImages.INSTANCE.sapos().getSafeUri().asString();
            case CHEMICAL:
                return MarkerImages.INSTANCE.chemical().getSafeUri().asString();
            case FACTORY:
                return MarkerImages.INSTANCE.factory().getSafeUri().asString();
            default:
                return MarkerImages.INSTANCE.marker().getSafeUri().asString();

        }
    }
}
